### PR TITLE
Install instructions using go get

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by bgentry** [comment]
@jgrahamc Alternatively, you can just move `httpdiff.go` into your project's root and drop the `src/`. I was gonna ask you why you had that directory but then found this issue instead :)

**Comment by drnic** [comment]
Yeah, would be more "go-like" to move the file into root folder; and then
its a simple, consistent "go get github.com/ORG/PROJ" installation command.
I didn't feel so bold as to submit a PR for that. But that's my preference
:)

On Tue, Mar 24, 2015 at 10:11 AM, Blake Gentry notifications@github.com
wrote:

> @jgrahamc https://github.com/jgrahamc Alternatively, you can just move
> httpdiff.go into your project's root and drop the src/. I was gonna ask
> you why you had that directory but then found this issue instead :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jgrahamc/httpdiff/pull/1#issuecomment-85603964.

## 

Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic

**Comment by ctrlrsf** [comment]
:+1:

**Comment by lukasz-madon** [comment]
@ctrlrsf you need to first `get` it.

**Comment by natefinch** [comment]
+1 to dropping to makefile, I filed an issue: https://github.com/jgrahamc/httpdiff/issues/2

**Comment by jgrahamc** [comment]
Happy to accept a pull request that moves stuff around, drops the Makefile.

**Pull request closed without merging**
